name: Build and Deploy
on:
  workflow_dispatch: {}
  push:
    branches:
      - web-port
    tags:
      - "v*"

concurrency:
  group: release-${{ github.ref }}
  cancel-in-progress: ${{ !startsWith(github.ref, 'refs/tags/') }}

permissions:
  contents: write
  pages: write

jobs:
  ci:
    uses: andrewiankidd/love2d4me/.github/workflows/love2d-ci.yml@master
    with:
      project_name: "Platformer"
      love_filename: "game"
      branch: "web-port"
